"""Text normalisation, ligature repair and other "the PDF lied to us" fixes.

PDF text extraction has a long list of well-known ways to produce text that
is *nearly* right.  Rather than patching each bad PDF, this module applies a
small set of general repairs, records what it changed, and leaves the result
inspectable -- a silent repair is just a different kind of bug.

The most important repair here is the ligature one.  Browsers printing to PDF
on macOS produce subset fonts whose ``cmap`` maps the ``ff`` ligature glyph
back to the ASCII double-quote, so ``different`` extracts as ``di"erent``.
That is invisible in a terminal but obvious on the rendered website, so we
normalise ligature code points *and* repair the intra-word quote artifact.
"""

from __future__ import annotations

import re
import unicodedata
from collections import Counter
from typing import Counter as CounterType
from typing import Dict, Optional

# ---------------------------------------------------------------------------
# Character-level repairs
# ---------------------------------------------------------------------------

#: Typographic ligatures -> their plain-ASCII expansions.
LIGATURES: Dict[str, str] = {
    "\ufb00": "ff",
    "\ufb01": "fi",
    "\ufb02": "fl",
    "\ufb03": "ffi",
    "\ufb04": "ffl",
    "\ufb05": "ft",
    "\ufb06": "st",
    "\u0132": "IJ",
    "\u0133": "ij",
    "\u0152": "OE",
    "\u0153": "oe",
    "\u00c6": "AE",
    "\u00e6": "ae",
}

#: Space-ish code points that should be ordinary spaces.  PDFs generated by
#: browsers are full of U+202F/NBSP, which breaks word matching and shows up
#: as a suspicious gap on the page.
SPACE_CHARS = {
    "\u00a0": " ",   # no-break space
    "\u2007": " ",   # figure space
    "\u2009": " ",   # thin space
    "\u200a": " ",   # hair space
    "\u202f": " ",   # narrow no-break space
    "\u2000": " ", "\u2001": " ", "\u2002": " ", "\u2003": " ",
    "\u2004": " ", "\u2005": " ", "\u2006": " ", "\u2008": " ",
    "\u3000": " ",   # ideographic space
    "\u200b": "",    # zero-width space
    "\ufeff": "",    # BOM / zero-width no-break space
    "\u00ad": "",    # soft hyphen
    "\u200e": "", "\u200f": "", "\u202a": "", "\u202b": "",
    "\u202c": "", "\u202d": "", "\u202e": "",
}

#: Dashes and quotes we normalise only for *matching*, never for display.
_MATCH_QUOTES = {
    "\u2018": "'", "\u2019": "'", "\u201a": "'", "\u201b": "'",
    "\u201c": '"', "\u201d": '"', "\u201e": '"', "\u201f": '"',
    "\u00ab": '"', "\u00bb": '"', "\u2039": "'", "\u203a": "'",
    "\u2032": "'", "\u2033": '"',
}
_MATCH_DASHES = {
    "\u2010": "-", "\u2011": "-", "\u2012": "-", "\u2013": "-",
    "\u2014": "-", "\u2015": "-", "\u2212": "-",
}

#: An ASCII double quote wedged *between two letters*.  This is the
#: macOS/browser ff-ligature artifact; genuine punctuation never occurs here
#: in English prose (an opening quote is preceded by a space or bracket, a
#: closing one is followed by one).
INTRAWORD_QUOTE_RE = re.compile(r'(?<=[A-Za-z])"(?=[A-Za-z])')

#: A hyphen at the end of a line followed by a lower-case word start is a
#: strong signal of a word broken across lines ("inter-\nnational").
LINE_HYPHEN_RE = re.compile(r'([A-Za-z])-$')

#: Hyphenation is much less likely when the tail after the hyphen is a
#: capital or the joined word would be implausibly long.
_SOFT_HYPHEN_MIN_LEFT = 2


def repair_text(text: str, stats: Optional[CounterType] = None) -> str:
    """Apply every display-safe repair to one run of extracted text.

    ``stats`` (a :class:`collections.Counter`) accumulates what was changed,
    keyed by a short human-readable label, so the caller can tell the user.
    """
    if not text:
        return text
    if stats is None:
        stats = Counter()

    original = text

    # 1. Ligature code points.
    for lig, plain in LIGATURES.items():
        if lig in text:
            stats["ligature"] += text.count(lig)
            text = text.replace(lig, plain)

    # 2. Odd spaces and invisible characters.
    for bad, good in SPACE_CHARS.items():
        if bad in text:
            stats["space"] += text.count(bad)
            text = text.replace(bad, good)

    # 3. The intra-word double-quote artifact.
    matches = INTRAWORD_QUOTE_RE.findall(text)
    if matches:
        stats["ligature"] += len(matches)
        text = INTRAWORD_QUOTE_RE.sub("ff", text)

    # 4. Control characters that have no business being on a page.  Keep
    #    tabs/newlines out of this helper's scope -- callers pass fragments.
    if any(ord(c) < 32 and c not in "\t\n\r" for c in text):
        stats["control"] += sum(1 for c in text if ord(c) < 32 and c not in "\t\n\r")
        text = "".join(c for c in text if ord(c) >= 32 or c in "\t\n\r")

    # 5. A subtle one: some PDFs put a combining mark before its base letter.
    if any(unicodedata.combining(c) for c in text):
        text = unicodedata.normalize("NFC", text)

    if text != original:
        stats.setdefault("changed_fragments", 0)
        stats["changed_fragments"] += 1
    return text


def clean_line(text: str, stats: Optional[CounterType] = None) -> str:
    """Repair a line and normalise its internal whitespace.

    Leading indentation is meaningful for paragraph detection, so only
    *internal* runs of spaces are collapsed and trailing space is dropped.
    """
    text = repair_text(text, stats)
    text = re.sub(r"[ \t]+", " ", text)
    return text.rstrip()


# ---------------------------------------------------------------------------
# Matching normalisation (lossy on purpose -- never used for display)
# ---------------------------------------------------------------------------

_PUNCT_TO_SPACE_RE = re.compile(r"[^0-9a-z]+")


def normalize_for_match(text: str) -> str:
    """Aggressively fold text for comparison.

    Lower-cases, expands ligatures, folds smart quotes and dashes, then
    replaces every remaining non-alphanumeric run with a single space.  Used
    for quote matching and duplicate detection only.
    """
    if not text:
        return ""
    out = []
    for ch in text:
        if ch in LIGATURES:
            out.append(LIGATURES[ch])
        elif ch in _MATCH_QUOTES:
            out.append(_MATCH_QUOTES[ch])
        elif ch in _MATCH_DASHES:
            out.append(_MATCH_DASHES[ch])
        elif ch in SPACE_CHARS:
            out.append(SPACE_CHARS[ch] or " ")
        else:
            out.append(ch)
    folded = "".join(out).lower()
    # Fold the ff-ligature artifact too, so that a paragraph extracted from a
    # broken font ("di"erent") normalises the same as the repaired text
    # ("different").  Without this, re-converting a PDF appears to change the
    # text and every annotation written against it stops matching.
    folded = INTRAWORD_QUOTE_RE.sub("ff", folded)
    return _PUNCT_TO_SPACE_RE.sub(" ", folded).strip()


def normalize_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def collapse_duplicate_spaces(text: str) -> str:
    return re.sub(r" {2,}", " ", text)


# ---------------------------------------------------------------------------
# Line joining (paragraph reflow)
# ---------------------------------------------------------------------------

def looks_like_hyphenation(left: str, right: str) -> bool:
    """Should ``left-`` + ``right`` be joined without the hyphen?"""
    left = left.rstrip()
    right = right.lstrip()
    if not left.endswith("-") or not right:
        return False
    # A trailing "-" after a single character is usually a dash/em-dash
    # fragment or a list marker, not hyphenation.
    stem = left.rstrip("-").rstrip()
    if len(stem) < _SOFT_HYPHEN_MIN_LEFT:
        return False
    if not stem[-1].isalpha():
        return False
    if not right[0].islower():
        # "Anglo-\nAmerican" is real hyphenation too, but it is far more
        # often a genuine compound; keeping the hyphen is the safe default.
        return False
    # Two hyphens in a row is a dash, not hyphenation.
    return not left.endswith("--")


def hyphenated_join(left: str, right: str) -> str:
    """The compound formed by joining ``left``'s trailing word to ``right``'s
    leading word across a line-break hyphen, without the hyphen."""
    stem = left.rstrip()[:-1].rstrip()
    word = re.search(r"[\w\u00c0-\u024f]+$", stem)
    tail = re.match(r"[\w\u00c0-\u024f]+", right.lstrip())
    if not word or not tail:
        return ""
    return f"{word.group(0)}-{tail.group(0)}".lower()


def join_lines(left: str, right: str, known_hyphenated=None) -> str:
    """Join two lines that belong to the same paragraph.

    ``known_hyphenated`` is the set of hyphenated compounds that appear
    *intact* elsewhere in the document ("self-determination").  A word that is
    a real compound keeps its hyphen even when the PDF broke the line there,
    because "selfdetermination" is not what the document says.
    """
    if not left:
        return right
    if not right:
        return left
    if looks_like_hyphenation(left, right):
        if known_hyphenated and hyphenated_join(left, right) in known_hyphenated:
            return left.rstrip() + right.lstrip()
        return left.rstrip()[:-1] + right.lstrip()
    return left.rstrip() + " " + right.lstrip()


# ---------------------------------------------------------------------------
# Small predicates used across stages
# ---------------------------------------------------------------------------

_PAGE_NUMBER_RES = [
    re.compile(r"^\s*[-–—]?\s*\d{1,4}\s*[-–—]?\s*$"),
    re.compile(r"^\s*page\s+\d{1,4}(\s+of\s+\d{1,4})?\s*$", re.IGNORECASE),
    re.compile(r"^\s*\d{1,4}\s*/\s*\d{1,4}\s*$"),
    re.compile(r"^\s*[ivxlcdm]{1,7}\s*$", re.IGNORECASE),
]


def looks_like_page_number(text: str) -> bool:
    stripped = (text or "").strip()
    if not stripped:
        return False
    if len(stripped) > 24:
        return False
    return any(rx.match(stripped) for rx in _PAGE_NUMBER_RES)


#: A line that ends in a section/page number and is mostly upper-case or
#: title-case is very likely a table-of-contents entry.
#: Trailing page number: either after dot leaders ("Article 5 .... 12") or
#: after a clear gap ("Final provisions   44").  A *single* space is not
#: enough -- "Article 36" is a heading, not a contents entry -- and getting
#: that wrong makes the tool delete real headings.
_TOC_TAIL_RE = re.compile(r"(?:\.{2,}|\s{2,})\s*\d{1,4}\s*$")
_TOC_LEADER_RE = re.compile(r"\.{3,}\s*\d{1,4}\s*$")


def looks_like_toc_entry(text: str) -> bool:
    stripped = (text or "").strip()
    if not stripped or len(stripped) > 160:
        return False
    if _TOC_LEADER_RE.search(stripped):
        return True
    return bool(_TOC_TAIL_RE.search(stripped))


#: "Page 3 of 12" style furniture, plus bare URLs printed in a page footer.
_URL_LINE_RE = re.compile(r"^\s*(https?://|www\.)\S+\s*$", re.IGNORECASE)
_PRINT_STAMP_RE = re.compile(
    r"^\s*\d{1,2}/\d{1,2}/\d{2,4},?\s+\d{1,2}:\d{2}\s*(am|pm)?\s*$", re.IGNORECASE
)


def looks_like_browser_furniture(text: str) -> bool:
    """Detect the header/footer a browser adds when printing to PDF.

    ``4/10/2025, 2:31 pm`` and ``https://example.org/page`` are not part of
    the document; leaving them in puts junk paragraphs on the website.
    """
    stripped = (text or "").strip()
    if not stripped:
        return False
    return bool(_PRINT_STAMP_RE.match(stripped) or _URL_LINE_RE.match(stripped))


def truncate_middle(text: str, width: int, ellipsis: str = "…") -> str:
    """Shorten ``text`` from the middle, keeping both ends readable.

    Long file paths matter more at their ends than in the middle, so the TUI
    uses this rather than a plain right-truncation.
    """
    if width <= 0:
        return ""
    if len(text) <= width:
        return text
    if width <= len(ellipsis) + 1:
        return text[:width]
    keep = width - len(ellipsis)
    left = (keep + 1) // 2
    right = keep - left
    return text[:left] + ellipsis + (text[-right:] if right else "")


def truncate_end(text: str, width: int, ellipsis: str = "…") -> str:
    if width <= 0:
        return ""
    if len(text) <= width:
        return text
    if width <= len(ellipsis):
        return text[:width]
    return text[: width - len(ellipsis)] + ellipsis
